
/**
 * @arg {string} label The first three characters of an Airtable element ID or the full ID.
 * @arg {Object} [options]
 * @arg {boolean} [options.fullSearch=false] Only checks for the most common types of IDs by default. Set to true to try retrieving the full backend categorization.
 * @return {string|Record<'prefix'|'name'|'sensitivity',string>|undefined}
 */

export function getAirtableIdType(label, options) {

    const labelArg = `${label}`.toLowerCase();

    const thisLabel = labelArg.length > 3
        ? labelArg.slice(0, 3)
        : labelArg.length === 3
            ? labelArg
            : new TypeError(`Expected the ID label to be 3 characters long, not ${labelArg.length} ("${labelArg}").`);

    if (thisLabel instanceof Error)
        throw thisLabel;

    const airtableIdPrefixes = {

        basic: {
            app: 'base',
            tbl: 'table',
            viw: 'view',
            fld: 'field',
            rec: 'record',
            att: 'attachment',
            sel: 'choice',
            usr: 'user',
            wsp: 'workspace'
        },

        all: [
            {
                prefix: "abr",
                name: "automatedBillingResetId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ach",
                name: "applicationChangeHookId",
                docsDescription: "An identifier for the webhook (WebhookId).",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "acr",
                name: "accessRequestId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "act",
                name: "actionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "adh",
                name: "applicationDisableHistoryCheckpointId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "adl",
                name: "auditLogConsumerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "atc",
                name: "attachmentsConsumerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "afs",
                name: "applicationFeatureSnapshotId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "app",
                name: "applicationId",
                docsDescription: "Base ID, a unique identifier for a base.",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ast",
                name: "assistantId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "asc",
                name: "applicationSandboxCommitId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "att",
                name: "attachmentId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "atm",
                name: "attachmentMetadataId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bbd",
                name: "blockBuildId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bbn",
                name: "blockBundleId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bbs",
                name: "blockBuilderServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bcp",
                name: "billingCouponId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bcr",
                name: "blockDeveloperCredentialRevisionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bdc",
                name: "blockDeveloperCredentialId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bdi",
                name: "blockBackendDeploymentInstanceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bdp",
                name: "blockBackendDeploymentPackageId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bee",
                name: "blockExecutionEnvironmentId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bip",
                name: "blockInstallationPageId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "biv",
                name: "blockInvocationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "blb",
                name: "blockBlobId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "blc",
                name: "blockCommitId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bld",
                name: "blockDeployId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bli",
                name: "blockInstallationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "blk",
                name: "blockId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "blm",
                name: "blockModuleId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "blp",
                name: "blockPackageId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "blr",
                name: "blockReleaseId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bls",
                name: "blockUnlistedMarketplaceLinkSecretId",
                sensitivity: "HIGH_CUSTOMER_DATA"
            }, {
                prefix: "blu",
                name: "blockUnlistedMarketplaceLinkId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bmd",
                name: "blockMetadataId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bpd",
                name: "backgroundPermanentDeletionServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "brd",
                name: "backgroundRowDeletionServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "brs",
                name: "blockRouterServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "brw",
                name: "browserId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bst",
                name: "blockReleaseStatusId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "btk",
                name: "blockBuilderServiceAccessToken",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bqy",
                name: "blockQueryId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pbq",
                name: "publicBlockQueryId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bud",
                name: "backgroundUserPermanentDeletionServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bvc",
                name: "billingVoucherCampaignId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bvr",
                name: "billingVoucherId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "bwc",
                name: "blockWorkingCopyId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "cdf",
                name: "colorDefinitionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "cds",
                name: "changeHookDeliveryServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "chg",
                name: "changeHooksConsumerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "chr",
                name: "cellHistoryRedactionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "clp",
                name: "clipboardDataId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "cls",
                name: "columnSetId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "cmk",
                name: "ekmScopeId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "com",
                name: "rowCommentId",
                docsDescription: "A comment ID",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "cre",
                name: "creditEventId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dbs",
                name: "dbShardId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dlp",
                name: "dataLossPreventionConsumerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "edt",
                name: "dataTableId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dvr",
                name: "domainVerificationRequestId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "eac",
                name: "externalAccountId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "etc",
                name: "externalAccountTypeConfigId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "eag",
                name: "externalAccountPermissionGrantId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "eat",
                name: "externalAccountTypeId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ets",
                name: "externalTableSyncId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pts"
            }, {
                prefix: "ect",
                name: "exploreCategoryId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "eml",
                name: "emailLogId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ent",
                name: "enterpriseAccountId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "eal",
                name: "enterpriseAuditLogTaskId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "eco",
                name: "enterpriseColorId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "etk",
                name: "enterpriseTaskId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "esn",
                name: "exploreSnapshotId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "evt",
                name: "eventTrackingId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ewt",
                name: "externalWebhookTriggerId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "exo",
                name: "exposureTrackingId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "exp",
                name: "exploreApplicationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ecf",
                name: "embeddingConfigId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "fec",
                name: "featureExtractionConsumerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "fep",
                name: "featureExtractionProducerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "fld",
                name: "columnId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pfl"
            }, {
                prefix: "flt",
                name: "filterId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "sfs",
                name: "savedFilterSetId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ftx",
                name: "featureExtractionServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "glv",
                name: "groupLevelId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "gcr",
                name: "globalRemovedUserContentRefId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "grp",
                name: "employeeGroupId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "idp",
                name: "ssoIdentityProviderId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "int",
                name: "slackIntegrationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "inv",
                name: "inviteId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "itr",
                name: "publicApiIteratorId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ivc",
                name: "invoiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "kdk",
                name: "kmsDataKeyId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "key",
                name: "userApiKey",
                sensitivity: "CRITICAL_HIGHLY_SENSITIVE"
            }, {
                prefix: "kub",
                name: "kubernetesClusterId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "lur",
                name: "licenseUpgradeRequestId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "men",
                name: "mentionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "not",
                name: "notificationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "oaa",
                name: "oauthAccessTokenId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "oap",
                name: "oauthApplicationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "oat",
                name: "oauthLegacyAccessToken",
                sensitivity: "CRITICAL_HIGHLY_SENSITIVE"
            }, {
                prefix: "otd",
                name: "otDocumentId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "otk",
                name: "externalOauthAccessTokenId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pat",
                name: "personalAccessTokenId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pbr",
                name: "publishedBlockReleaseId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pds",
                name: "publishedDatasetId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pgl",
                name: "pageLoadId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pln",
                name: "billingPlanId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "adn",
                name: "billingAddOnId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ptl",
                name: "portalId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pro",
                name: "processId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "qry",
                name: "queryId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rcp",
                name: "receiptId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rdm",
                name: "reliabilityDashboardMetricId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rma",
                name: "reliabilityDashboardMetricAnnotationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rol",
                name: "roleId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rec",
                name: "rowId",
                docsDescription: "Record ID",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rtp",
                name: "rowTemplateId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "prt"
            }, {
                prefix: "ret",
                name: "retentionRequestId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "req",
                name: "requestId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "rts",
                name: "realtimeServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "sel",
                name: "choiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "siv",
                name: "scriptInvocationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ses",
                name: "sessionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "shr",
                name: "shareId",
                sensitivity: "CRITICAL_HIGHLY_SENSITIVE"
            }, {
                prefix: "ski",
                name: "assistantSkillId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "snp",
                name: "appBackupSnapshotId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "soc",
                name: "secretSocketId",
                sensitivity: "CRITICAL_HIGHLY_SENSITIVE"
            }, {
                prefix: "spa",
                name: "internalSpanGuid",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "srt",
                name: "sortId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "svc",
                name: "serviceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "tbl",
                name: "tableId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "ptb"
            }, {
                prefix: "tfa",
                name: "twoFactorStrategyId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "too",
                name: "assistantToolId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "thr",
                name: "threadId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "trc",
                name: "internalTraceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "usr",
                name: "userId",
                docsDescription: "A user ID",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "tsk",
                name: "taskId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "twk",
                name: "taskworkerServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "uce",
                name: "userContentGcExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "uco",
                name: "userContentObjectId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ucr",
                name: "userContentRefId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ugp",
                name: "userGroupId",
                docsDescription: "A user group ID",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ulp",
                name: "unifiedEventLogPayloadId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "viw",
                name: "viewId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pvw"
            }, {
                prefix: "vsc",
                name: "viewSectionId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pvs"
            }, {
                prefix: "wac",
                name: "workflowActionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wat",
                name: "workflowActionTypeId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wax",
                name: "workflowActionExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wbr",
                name: "workflowBranchId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wde",
                name: "workflowDecisionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wdt",
                name: "workflowDecisionTypeId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wdx",
                name: "workflowDecisionExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wch",
                name: "workerChildId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "web",
                name: "webServerId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wes",
                name: "workflowExecutionServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wfd",
                name: "workflowDeploymentId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wfl",
                name: "workflowId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pwf"
            }, {
                prefix: "wfx",
                name: "workflowExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wgr",
                name: "workflowGraphId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wgx",
                name: "workflowGraphExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wkr",
                name: "workerId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wpg",
                name: "workflowNodeExecutionPayloadGroupId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wnp",
                name: "workflowNodeExecutionPayloadId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wne",
                name: "workflowNodeTestExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wns",
                name: "workflowNodeSelectedTestDataId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wtc",
                name: "workflowTriggerConnectionId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pwc"
            }, {
                prefix: "wtx",
                name: "workflowTestExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wgt",
                name: "workflowGraphTestExecutionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wrg",
                name: "workflowTriggerRegistrationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wsp",
                name: "workspaceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wst",
                name: "workspaceTrialId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wtr",
                name: "workflowTriggerId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wtt",
                name: "workflowTriggerTypeId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "wsc",
                name: "workflowSectionId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "pws"
            }, {
                prefix: "wwi",
                name: "workflowWebhookInvocationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pkg",
                name: "packageId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pkr",
                name: "packageReleaseId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pki",
                name: "packageInstallationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pcv",
                name: "packageCustomizationVariableId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pag",
                name: "pageId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "ppg"
            }, {
                prefix: "pbd",
                name: "pageBundleId",
                sensitivity: "LOW_INTERNAL",
                packageModelIdPrefix: "ppb"
            }, {
                prefix: "pbs",
                name: "pageBundleSharingIntentId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pgr",
                name: "pageRevisionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pel",
                name: "pageElementId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "peo",
                name: "pageElementOutputId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pbk",
                name: "pageBookmarkId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ple",
                name: "pageLayoutElementRowId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plr",
                name: "pageLayoutColumnsRowId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plc",
                name: "pageLayoutColumnId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plo",
                name: "pageLayoutRowCanvasId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plf",
                name: "pageLayoutFullCanvasElementId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pla",
                name: "pageLayoutCanvasAreaId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plh",
                name: "pageLayoutHorizontalBarId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pli",
                name: "pageLayoutHorizontalBarRowId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plj",
                name: "pageLayoutHorizontalBarElementId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pls",
                name: "pageLayoutSlotElementId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "plv",
                name: "pageLayoutCanvasId",
                sensitivity: "LOW_INTERNAL",
                deprecated: !0
            }, {
                prefix: "psc",
                name: "pageSectionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "upr",
                name: "upgradeRequestId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "fcs",
                name: "fakeCdnServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "fki",
                name: "featureKitInstallationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "fka",
                name: "featureKitAnswerId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "nac",
                name: "notificationActionId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "acn",
                name: "actionableNotificationId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "nie",
                name: "notificationInteractiveElementId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pxu",
                name: "proxySqlConfigUpdaterServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "pxs",
                name: "proxySqlSmokeTestServiceId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dds",
                name: "dateDependencySettingsId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dtr",
                name: "dataTableRecordId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dir",
                name: "dataTableImportRunId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dtt",
                name: "dataTableTaskId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dsi",
                name: "dataTableSearchIndexId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "ecs",
                name: "embeddingConfigStorageId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dtl",
                name: "dataTableWriterLeaseId",
                sensitivity: "LOW_INTERNAL"
            }, {
                prefix: "dtc",
                name: "dataTableConnectionId",
                sensitivity: "LOW_INTERNAL"
            }
        ]

    };

    const prefixPool = airtableIdPrefixes[options?.fullSearch === true ? 'all' : 'basic'];

    const match = Array.isArray(prefixPool) ? prefixPool.find(o => o.prefix.match(thisLabel)) : prefixPool[thisLabel];

    return match ?? new ReferenceError(`Failed to find a match for the "${thisLabel}" label with ${!!options?.fullSearch ? 'full' : 'basic'} prefix search .`);

};
